MAJOR_MINOR_PATCH_VERSION = r"\d+\.\d+\.\d+"

LONG = "--version"
SHORT = "-V"


VERSION_WITH_THREE_NUMBERS_AND_DOTS = MAJOR_MINOR_PATCH_VERSION
VERSION_WITH_V_PREFIX = r"v" + r"(" + MAJOR_MINOR_PATCH_VERSION + r")"
